name: Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  # 1) Install dependencies (caches optional)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd playwright
          npm install

    outputs:
      dummy-output: 'done'

  # 2) Desktop tests (Chromium + Firefox, excluding performance)
  desktop-tests:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies (again)
        run: |
          cd playwright
          npm install
      - name: Run all except mobile-chrome & performance
        run: |
          cd playwright
          npx playwright test --project=chromium --project=firefox --grep-invert="@performance"

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-desktop
          path: playwright/playwright-report

  # 3) Mobile tests (mobile-chrome, excluding performance)
  mobile-tests:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Run mobile-chrome tests
        run: |
          cd playwright
          npx playwright test --project=mobile-chrome --grep-invert="@performance"

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-mobile
          path: playwright/playwright-report

  # 4) Performance tests (Chromium only, focusing on @performance)
  performance-tests:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Run performance tests on chromium
        run: |
          cd playwright
          npx playwright test --project=chromium --grep="@performance"

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-performance
          path: playwright/playwright-report

  # 5) K6 test (if needed)
  k6-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run K6 test
        run: |
          docker run --rm -v "$(pwd)/K6:/scripts" grafana/k6 run /scripts/performance-test.js
