name: Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  cache-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Playwright Docker Image
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: playwright-docker-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            playwright-docker-${{ runner.os }}-

      - name: Pre-pull Playwright Docker Image
        run: |
          docker pull mcr.microsoft.com/playwright:v1.50.1-noble

  desktop-tests:
    runs-on: ubuntu-latest
    needs: cache-docker
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Run desktop tests (excluding bugs)
        run: |
          cd playwright
          HOME=/root npx playwright test --project=chromium --project=firefox --grep-invert="@bug|@visual|@performance"

      - name: Upload HTML report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-desktop-no-bugs
          path: playwright/playwright-report

  desktop-tests-bug:
    runs-on: ubuntu-latest
    needs: cache-docker
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Run desktop tests (only bugs)
        run: |
          cd playwright
          HOME=/root npx playwright test --project=chromium --project=firefox --grep="@bug"

      - name: Upload HTML report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-desktop-bugs
          path: playwright/playwright-report

  visual-comparison:
    runs-on: ubuntu-latest
    needs: cache-docker
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Run visual comparison test (Chromium only)
        run: |
          cd playwright
          npx playwright test tests/visual-comparison.spec.ts --project=chromium

      - name: Upload visual test screenshots (only if test fails)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-test-screenshots
          path: playwright/screenshots/

  performance-tests:
    runs-on: ubuntu-latest
    needs: cache-docker
    container:
      image: mcr.microsoft.com/playwright:v1.50.1-noble
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd playwright
          npm install

      - name: Run performance tests on chromium
        run: |
          cd playwright
          npx playwright test --project=chromium --grep="@performance"

      - name: Upload HTML report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-performance
          path: playwright/playwright-report

  deploy-reports:
    runs-on: ubuntu-latest
    needs: [desktop-tests, desktop-tests-bug, visual-comparison, performance-tests]
    if: always()
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download desktop tests (excluding bugs)
        uses: actions/download-artifact@v4
        with:
          name: playwright-html-report-desktop-no-bugs
          path: gh-pages-reports/desktop-no-bugs

      - name: Download desktop bug tests
        uses: actions/download-artifact@v4
        with:
          name: playwright-html-report-desktop-bugs
          path: gh-pages-reports/desktop-bugs

      - name: Download visual comparison screenshots
        uses: actions/download-artifact@v4
        with:
          name: visual-test-screenshots
          path: gh-pages-reports/visual

      - name: Download performance report
        uses: actions/download-artifact@v4
        with:
          name: playwright-html-report-performance
          path: gh-pages-reports/performance

      - name: Generate index.html for reports
        run: |
          echo "<html><head><title>Test Reports</title></head><body>" > gh-pages-reports/index.html
          echo "<h1>Test Reports</h1>" >> gh-pages-reports/index.html
          echo "<ul>" >> gh-pages-reports/index.html
          echo "<li><a href='desktop-no-bugs/index.html'>Desktop Test Report (No Bugs)</a></li>" >> gh-pages-reports/index.html
          echo "<li><a href='desktop-bugs/index.html'>Desktop Bug Report</a></li>" >> gh-pages-reports/index.html
          echo "<li><a href='visual/'>Visual Test Screenshots</a></li>" >> gh-pages-reports/index.html
          echo "<li><a href='performance/index.html'>Performance Test Report</a></li>" >> gh-pages-reports/index.html
          echo "</ul></body></html>" >> gh-pages-reports/index.html

      - name: Deploy failed visual tests to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: playwright/screenshots/
          clean: true
          token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}

  k6-tests:
    runs-on: ubuntu-latest
    needs: cache-docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run K6 test
        run: |
          docker run --rm -v "$(pwd)/K6:/scripts" grafana/k6 run /scripts/performance-test.js
